<?
$GLOBALS["codekeepers_block_id"] = array(
    'banners_banner_main_id' => '2',
    'catalog_goods_id' => '14',
    'content_features1' => '3',
    'content_services_id' => '15',
    'content_team_id' => '7',
    'content_blog_id' => '4',
    'content_sidebar-phone_id' => '#SIDEBAR-PHONE_IBLOCK_ID#',
    'content_projects_id' => '6',
    'content_reviews_id' => '19',
    'content_about_id' => '8',
    'content_features_id' => '#FEATURES_IBLOCK_ID#',
    'content_partners_id' => '#PARTNERS_IBLOCK_ID#',
    'content_call-to-action_id' => '#CALL-TO-ACTION_IBLOCK_ID#',
    'content_faq_id' => '#FAQ_IBLOCK_ID#',
    'content_timeline_id' => '#TIMELINE_IBLOCK_ID#',
    'content_why-us_id' => '#WHY-US_IBLOCK_ID#',
    'content_stats_id' => '#STATS_IBLOCK_ID#',
    'content_career_id' => '17',
    'content_discount_id' => '#DISCOUNT_IBLOCK_ID#',
    'content_licence_id' => '18',
    'content_contacts_id' => '#CONTACTS_IBLOCK_ID#',
    'content_discounts_id' => '#DISCOUNTS_IBLOCK_ID#',
    'content_timeline-block_id' => '#TIMELINE-BLOCK_IBLOCK_ID#',
    'settings_messengers_id' => '12',
    'settings_social_id' => '13',
    'settings_main_id' => '1',
    'settings_main_element_id' => '14',
    'requests_feedback_id' => '16',
)
?>