<?
$GLOBALS["codekeepers_block_id"] = array(
    'banners_banner_main_id' => '2',
    'banners_banner_call-to-action_id' => '22',
    'content_blog_id' => '4',
    'content_features1_id' => '3',
    'content_features-block_id' => '5',
    'content_services_id' => '15',
    'content_team_id' => '7',
    'content_projects_id' => '6',
    'content_reviews_id' => '19',
    'content_about_id' => '8',
    'content_partners_id' => '24',
    'content_faq_id' => '9',
    'content_faq-block_id' => '10',
    'content_pricing_id' => '11',
    'content_career_id' => '17',
    'content_licence_id' => '18',
    'content_gallery_id' => '21',
    'catalog_goods_id' => '14',
    'settings_messengers_id' => '12',
    'settings_social_id' => '13',
    'settings_main_id' => '1',
    'settings_main_element_id' => '14',
    'widgets_sidebar-contacts_id' => '20',
    'requests_feedback_id' => '16',
)
?>